//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsService.ServiceRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="People", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
    [System.SerializableAttribute()]
    public partial class People : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Right {
            get {
                return this.RightField;
            }
            set {
                if ((this.RightField.Equals(value) != true)) {
                    this.RightField = value;
                    this.RaisePropertyChanged("Right");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="News", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
    [System.SerializableAttribute()]
    public partial class News : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> AuthorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BodyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Author {
            get {
                return this.AuthorField;
            }
            set {
                if ((this.AuthorField.Equals(value) != true)) {
                    this.AuthorField = value;
                    this.RaisePropertyChanged("Author");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Body {
            get {
                return this.BodyField;
            }
            set {
                if ((object.ReferenceEquals(this.BodyField, value) != true)) {
                    this.BodyField = value;
                    this.RaisePropertyChanged("Body");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubTitle {
            get {
                return this.SubTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.SubTitleField, value) != true)) {
                    this.SubTitleField = value;
                    this.RaisePropertyChanged("SubTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceRef.INewsWCF")]
    public interface INewsWCF {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsWCF/createUser", ReplyAction="http://tempuri.org/INewsWCF/createUserResponse")]
        void createUser(string firstname, string lastname, string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsWCF/createUser", ReplyAction="http://tempuri.org/INewsWCF/createUserResponse")]
        System.Threading.Tasks.Task createUserAsync(string firstname, string lastname, string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsWCF/connectUser", ReplyAction="http://tempuri.org/INewsWCF/connectUserResponse")]
        WindowsService.ServiceRef.People connectUser(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsWCF/connectUser", ReplyAction="http://tempuri.org/INewsWCF/connectUserResponse")]
        System.Threading.Tasks.Task<WindowsService.ServiceRef.People> connectUserAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsWCF/getNews", ReplyAction="http://tempuri.org/INewsWCF/getNewsResponse")]
        WindowsService.ServiceRef.News[] getNews();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsWCF/getNews", ReplyAction="http://tempuri.org/INewsWCF/getNewsResponse")]
        System.Threading.Tasks.Task<WindowsService.ServiceRef.News[]> getNewsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsWCF/getHistoric", ReplyAction="http://tempuri.org/INewsWCF/getHistoricResponse")]
        WindowsService.ServiceRef.News[] getHistoric(WindowsService.ServiceRef.People user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsWCF/getHistoric", ReplyAction="http://tempuri.org/INewsWCF/getHistoricResponse")]
        System.Threading.Tasks.Task<WindowsService.ServiceRef.News[]> getHistoricAsync(WindowsService.ServiceRef.People user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsWCF/sendNews", ReplyAction="http://tempuri.org/INewsWCF/sendNewsResponse")]
        void sendNews(WindowsService.ServiceRef.News news, WindowsService.ServiceRef.People people);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsWCF/sendNews", ReplyAction="http://tempuri.org/INewsWCF/sendNewsResponse")]
        System.Threading.Tasks.Task sendNewsAsync(WindowsService.ServiceRef.News news, WindowsService.ServiceRef.People people);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsWCF/sendNewsA", ReplyAction="http://tempuri.org/INewsWCF/sendNewsAResponse")]
        void sendNewsA(WindowsService.ServiceRef.News news, string author);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsWCF/sendNewsA", ReplyAction="http://tempuri.org/INewsWCF/sendNewsAResponse")]
        System.Threading.Tasks.Task sendNewsAAsync(WindowsService.ServiceRef.News news, string author);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INewsWCFChannel : WindowsService.ServiceRef.INewsWCF, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NewsWCFClient : System.ServiceModel.ClientBase<WindowsService.ServiceRef.INewsWCF>, WindowsService.ServiceRef.INewsWCF {
        
        public NewsWCFClient() {
        }
        
        public NewsWCFClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NewsWCFClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NewsWCFClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NewsWCFClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void createUser(string firstname, string lastname, string username, string password) {
            base.Channel.createUser(firstname, lastname, username, password);
        }
        
        public System.Threading.Tasks.Task createUserAsync(string firstname, string lastname, string username, string password) {
            return base.Channel.createUserAsync(firstname, lastname, username, password);
        }
        
        public WindowsService.ServiceRef.People connectUser(string username, string password) {
            return base.Channel.connectUser(username, password);
        }
        
        public System.Threading.Tasks.Task<WindowsService.ServiceRef.People> connectUserAsync(string username, string password) {
            return base.Channel.connectUserAsync(username, password);
        }
        
        public WindowsService.ServiceRef.News[] getNews() {
            return base.Channel.getNews();
        }
        
        public System.Threading.Tasks.Task<WindowsService.ServiceRef.News[]> getNewsAsync() {
            return base.Channel.getNewsAsync();
        }
        
        public WindowsService.ServiceRef.News[] getHistoric(WindowsService.ServiceRef.People user) {
            return base.Channel.getHistoric(user);
        }
        
        public System.Threading.Tasks.Task<WindowsService.ServiceRef.News[]> getHistoricAsync(WindowsService.ServiceRef.People user) {
            return base.Channel.getHistoricAsync(user);
        }
        
        public void sendNews(WindowsService.ServiceRef.News news, WindowsService.ServiceRef.People people) {
            base.Channel.sendNews(news, people);
        }
        
        public System.Threading.Tasks.Task sendNewsAsync(WindowsService.ServiceRef.News news, WindowsService.ServiceRef.People people) {
            return base.Channel.sendNewsAsync(news, people);
        }
        
        public void sendNewsA(WindowsService.ServiceRef.News news, string author) {
            base.Channel.sendNewsA(news, author);
        }
        
        public System.Threading.Tasks.Task sendNewsAAsync(WindowsService.ServiceRef.News news, string author) {
            return base.Channel.sendNewsAAsync(news, author);
        }
    }
}
